raycast/ray-so

app/(navigation)/(code)/code.tsx
app/(navigation)/icon/icon-generator.tsx
app/(navigation)/themes/layout.tsx

- Added "Source Code" links to the navigation now that [ray.so is open source 🎉](https://twitter.com/rauchg/status/1808147941863088249)
- In the icon maker layout things were tight, let me know if the `2xl` breakpoint is acceptable
https://github.com/raycast/ray-so/assets/13041/8e569484-bc7d-4a9b-b704-f5fcba8ddd46

Add Github source code links to navigation layouts

---

app/(navigation)/(code)/components/Editor.module.css
app/(navigation)/(code)/components/Editor.tsx
app/(navigation)/(code)/components/HighlightedCode.tsx

Fixes missing `color` tokens for plain text. 
Line numbers don't work in this mode either so remove eventual padding.

#78 Fix plain text color bug

---

app/(navigation)/(code)/util/languages.ts

- Modified app/(navigation)/(code)/util/languages.ts and added dart in LANGUAGES object
```
dart: {
name: "Dart",
className: "diff",
src: () => import("shiki/langs/dart.mjs"),
},
```

Added support for dartlang syntax highlighting

---

app/(navigation)/(code)/components/ExportButton.tsx

When I have a very long code snippet that needs to generate an image, I cannot directly copy the image to the clipboard, as shown in the video below
Before
https://github.com/user-attachments/assets/32ed9105-230f-431d-a467-89314e372048
After I fix 
https://github.com/user-attachments/assets/5d932683-9530-4f28-8604-6b684ab19421

fix: resolve issue with copying long text images to clipboard

---

app/(navigation)/(code)/components/ExportButton.tsx

Apple's Clipboard API expects a Promise when writing to the clipboard, therefore I adapted the function to accommodate for this. 
I've tested on:
- Safari - Version 18.0 (20619.1.26.31.6)
- Edge - Version 128.0.2739.67 (Official build) (arm64)
- Chrome - Version 128.0.6613.121 (Official Build) (arm64)
This fixes #130

fix for Copy Image on Safari (#130)

---

app/(navigation)/(code)/components/Frame.module.css

Background images used in Clerk and Tailwind themes had pointer events, so you could right click and save/copy the image asset.

Remove pointer events from partner theme backgrounds

---

app/(navigation)/icon/components/ExportModal.tsx
app/(navigation)/icon/icon-generator.tsx
app/(navigation)/icon/save-svg-as-png.d.ts
package-lock.json
package.json

Replaces outdated svg-to-png library with the same one we use for code images exports. This fixes an issue where icons in Icon Maker were always 16x16px regardless of size in Safari

Fix exported icon size in safari

---

app/(navigation)/(code)/util/languages.ts

Added support for Move, which is supported by Shiki already: https://shiki.style/languages
See screenshot for an example.

Add support for Move language

---

app/(navigation)/quicklinks/quicklinks.ts

This was previously incorrectly describing the user's home folder as the root of the drive. This separates the previous quicklinks, both opening in Finder and in File Search, into _Open Home_ and _Open Root_ variants, with Home being `~/` and Root being `/`.

Fix Root quicklink, add Home quicklink

---

app/(navigation)/quicklinks/quicklinks.ts

Hi folks 👋
I'd like to add a quicklink to provide a fast access to the Kotlin Documentation: https://kotlinlang.org/docs/home.html

Add Kotlin Documentation quicklink

---

app/(navigation)/(code)/util/formatCode.ts
package-lock.json
package.json

Adding support for formatting Python code using Ruff.
Ruff is a rust based fast python formatter. They also have a wasm build of the same. Built by the Astral team (Charlie Marsh)
ruff repo: https://github.com/astral-sh/ruff
Note:
- Currently there are console logs from somewhere deep inside ruff wasm. I already asked on Astral discord on how to turn off that log - https://discord.com/channels/1039017663004942429/1340080349534748702

Add "format code" support for Python

---

app/(navigation)/prompts/prompts.ts

This pull request adds new prompt configurations to the `music` array in the `prompts.ts` file. These prompts are designed to facilitate copying the currently playing track's URL between Apple Music and Spotify.
New prompt configurations:
* Added a prompt to copy the Spotify URL from the currently playing Apple Music track. (`app/(navigation)/prompts/prompts.ts`)
* Added a prompt to copy the Apple Music URL from the currently playing Spotify track. (`app/(navigation)/prompts/prompts.ts`)

Add music prompts (cross copy current track url)

---

app/(navigation)/themes/components/add-to-raycast.tsx
app/(navigation)/themes/components/redirect-to-raycast.tsx
app/(navigation)/themes/lib/url.ts

@KELiON I could do with you or someone sanity checking this as I'm not familiar with the recent changes.
I tested the change locally and it works, although I'm not entirely sure on the purpose of the `RedirectToRaycast` component without diving further into things.
I checked out your PR #204 which makes similar changes.
Whitespace changes were automatically made by the editor, removed a blank line too.
This fixes an issue reported on [Slack](https://raycastcommunity.slack.com/archives/C01A0R0NXGQ/p1742128696682399) with being unable to add themes to Raycast.

Await detection of Raycast flavor

---

app/(navigation)/quicklinks/quicklinks.ts

Adding a new subsection, "Science", to Quicklinks with several useful links to search scientific databases and literature search. For now, it is mostly focused on bioinformatics and medical genomics resources.

Adding a new Science Quicklinks

---

app/(navigation)/snippets/[[...slug]]/snippets.tsx

Hello @KELiON ,
I've created a fix for the Raycast snippet import functionality that was failing. The issue was that we weren't properly awaiting the `getRaycastFlavor()` Promise before attempting to navigate to the Raycast URL.
**Before:**
https://github.com/user-attachments/assets/e7ad02a1-29ca-45d9-8e22-59191cc0da43 
**After:**
https://github.com/user-attachments/assets/96051f31-1b68-4b62-b99f-259a02599965
- Ensured proper async/await in `handleAddToRaycast()`
The fix is minimal and focused only on the async behavior. Please let me know if you need any clarification or have suggestions for improvement.
Thanks for your time!

Fix: await getRaycastFlavor promise before snippet import navigation

---

app/(navigation)/(code)/components/FormatCodeButton.tsx

Sonner API changed so that custom errors from the formatter weren't visible anymore. E.g when making a syntax error or trying to format a language with the incorrect language set.
This PR updates the error callback to return the custom code block as the toast description instead of replacing the whole toast

Fix missing formatting error after sonner upgrade

---

app/(navigation)/quicklinks/components/quicklink.tsx
app/(navigation)/quicklinks/shared/page.tsx
app/(navigation)/quicklinks/shared/shared.tsx
app/(navigation)/quicklinks/utils/isValidLink.ts

Fixes an issue when sharing quicklinks with dynamic arguments as part of the host would crash e.g.
` https://{argument name="website" options="raycast, google" default="raycast"}.com`

Fix crash when sharing quicklinks

---

app/(navigation)/(code)/util/languages.ts

It's a good point that sharing terminal output as screenshots can be inconvenient. Having a direct way to view it on ray.so would be really helpful.
That's why I've added the `console` language, which is also known as `shellsession` or `shell-session` in other contexts.

Add language support for console(shell session)

---

app/(navigation)/(code)/components/Editor.module.css
app/(navigation)/(code)/components/Editor.tsx
app/(navigation)/(code)/components/Frame.module.css

Previously if you put a single line of code you'd get extra padding below due to the textarea defaulting to two rows. This PR improves this by setting the initial rows to 1 and making the frame only use as much space as needed by the code.
before: 
after:

Allow single line code blocks

---

app/(navigation)/icon/icon-generator.tsx

- Users can now generate icons using text (max 2 characters, e.g., `A`, `BM`).
- Text is rendered inside the icon in place of a graphic or icon.
- Existing color customization support applies to text as well.
- Works seamlessly with the previous icon customization flow.
- Font and style are consistent across all icons.
https://github.com/user-attachments/assets/d8b9fd5a-30f0-41cc-915a-ae2e47313b35

feat: add support for generating icons from text
